# Copyright Siemens AG, 2014
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: c

cache:
 - apt

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper libglib2.0-dev libmagic-dev libxml2-dev
        libtext-template-perl librpm-dev  rpm libpcre3-dev libssl-dev
        apache2 libapache2-mod-php5 php5-pgsql php-pear php5-cli
        binutils bzip2 cabextract cpio sleuthkit genisoimage poppler-utils
        rpm upx-ucl unrar-free unzip p7zip-full p7zip wget git-core subversion
        postgresql libpq-dev
 - sudo apt-get install -qq cppcheck

script:
 - make
 - sudo chown fossy:fossy /usr/local/etc/fossology/Db.conf
 - cppcheck -q -isrc/nomos/agent_tests/testdata/NomosTestfiles/ src/

